name: Deploy to EC2

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
    paths-ignore:
        - 'airflow/**'  

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "[START] deployment to EC2"
      run: echo "Starting deployment to EC2..."  

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: "[SUCCESS] Checkout"
      run: echo "[SUCCESS] checkout to main branch"    

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Connecting to EC2 for deployment
      run: echo "Connecting to EC2 for deployment"

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          echo "Moving to project directory..."
          cd /home/ubuntu/workspace/yoon/mlops-project-mlops-2

          echo ""
          branch_name=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
          echo "[EC2][Branch][now] : $branch_name"
          echo ""

          echo "[EC2][Branch][checkout]"
          git fetch origin main
          git checkout -B main origin/main

          echo ""
          echo "[EC2][Recent Commit info] : $(git log -1 --oneline)"
          echo ""

          if [ -f requirements.txt ]; then 
            pip install --upgrade -r requirements.txt; 
          fi

          echo "[STATUS][before restart]"
          sudo systemctl status myapp --no-pager | head -n 5
          echo ""
          sudo systemctl restart myapp
          echo ""
          echo "[STATUS][after restart]"
          sudo systemctl status myapp --no-pager | head -n 5
        
        EOF
